/**
 * reportDownload — client-side .md / .pdf export of a single composition/report
 * (S7-T3, reclaiming the affordance the older UI had).
 *
 * No new external host is touched (the CSP forbids remote fetches): the Markdown
 * is a Blob object-URL download, and the PDF is a browser print of a
 * self-contained, inline-styled HTML document opened in a popup — "Save as PDF"
 * from the print dialog. If the popup is blocked, the caller falls back to the
 * .md download (the floor). All DOM-free string building lives here so it is
 * unit-testable; only the two side-effecting helpers touch the browser.
 */
import { citationKindLabel, isGroundingCitation, type Citation } from '@/lib/citationsModel'

export interface ReportDoc {
  title: string
  /** Markdown body (may carry `[N]` / `[[ref:N]]` markers). */
  body: string
  /** ISO / display timestamp string, when known. */
  producedAt?: string | null
  severity?: string | null
  /** Scope label, e.g. "country_g20_us · country assessment". */
  scope?: string | null
  citations?: Citation[]
}

/** A filesystem-safe slug for the filename. */
function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'report'
  )
}

const stamp = () => new Date().toISOString().slice(0, 10)

/** Build the Markdown export (front-matter-ish header + body + an Evidence list
 *  so the inline `[N]` / `[[ref:N]]` markers resolve on paper). */
export function reportToMarkdown(doc: ReportDoc): string {
  const lines: string[] = []
  lines.push(`# ${doc.title || 'Legba Report'}`)
  lines.push('')
  const meta: string[] = []
  if (doc.scope) meta.push(doc.scope)
  if (doc.severity) meta.push(`severity: ${doc.severity}`)
  if (doc.producedAt) meta.push(`as of ${doc.producedAt}`)
  meta.push(`exported ${new Date().toLocaleString()}`)
  lines.push(`_${meta.join(' · ')}_`)
  lines.push('')
  lines.push(doc.body?.trim() || '_(no written body)_')
  const cites = doc.citations ?? []
  if (cites.length > 0) {
    lines.push('')
    lines.push('## Evidence')
    lines.push('')
    for (const c of cites) {
      // A grounding block has no id and no url, so `c.title ?? c.refId` used
      // to fall through to an empty string. Name the KIND and the set it
      // resolves against instead — a downloaded report has no citation record
      // to join against, so the line has to carry it.
      const bits = [c.title ?? (c.refId || citationKindLabel(c))]
      if (isGroundingCitation(c)) {
        bits.push(
          `desk grounding · ${citationKindLabel(c)} · resolves against ${
            c.resolvesAgainst ?? "this finding's citation record"
          }`,
        )
      }
      if (c.source) bits.push(c.source)
      if (typeof c.effectiveConfidence === 'number') {
        bits.push(`effective_confidence ${Math.round(c.effectiveConfidence * 100)}%`)
      }
      lines.push(`- **${c.marker}** — ${bits.join(' · ')}`)
    }
  }
  lines.push('')
  lines.push('---')
  lines.push('_Generated by Legba — a decompositional intelligence oracle._')
  return lines.join('\n')
}

/** Escape a string for safe HTML text content. */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * A minimal, dependency-free Markdown→HTML for the print document. Handles the
 * subset compositions actually emit — ATX headings, bold/italic, bullet &
 * ordered lists, and paragraphs. Everything is HTML-escaped first, so this can
 * never inject markup. Not a full CommonMark engine — intentionally small.
 */
export function miniMarkdownToHtml(md: string): string {
  const inline = (s: string): string =>
    esc(s)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
  const out: string[] = []
  let list: 'ul' | 'ol' | null = null
  const closeList = () => {
    if (list) {
      out.push(`</${list}>`)
      list = null
    }
  }
  for (const raw of (md ?? '').split(/\r?\n/)) {
    const line = raw.trimEnd()
    if (line.trim() === '') {
      closeList()
      continue
    }
    const h = /^(#{1,6})\s+(.*)$/.exec(line)
    if (h) {
      closeList()
      const level = h[1].length
      out.push(`<h${level}>${inline(h[2])}</h${level}>`)
      continue
    }
    const ul = /^\s*[-*+]\s+(.*)$/.exec(line)
    if (ul) {
      if (list !== 'ul') {
        closeList()
        out.push('<ul>')
        list = 'ul'
      }
      out.push(`<li>${inline(ul[1])}</li>`)
      continue
    }
    const ol = /^\s*\d+[.)]\s+(.*)$/.exec(line)
    if (ol) {
      if (list !== 'ol') {
        closeList()
        out.push('<ol>')
        list = 'ol'
      }
      out.push(`<li>${inline(ol[1])}</li>`)
      continue
    }
    closeList()
    out.push(`<p>${inline(line)}</p>`)
  }
  closeList()
  return out.join('\n')
}

/** Build the full self-contained print HTML document (inline CSS; no remote
 *  assets, CSP-safe). */
export function reportToPrintHtml(doc: ReportDoc): string {
  const metaBits: string[] = []
  if (doc.scope) metaBits.push(esc(doc.scope))
  if (doc.severity) metaBits.push(`severity: ${esc(doc.severity)}`)
  if (doc.producedAt) metaBits.push(`as of ${esc(doc.producedAt)}`)
  const cites = doc.citations ?? []
  const evidence =
    cites.length > 0
      ? `<h2>Evidence</h2><ol class="evidence">${cites
          .map((c) => {
            const parts = [esc(c.title ?? (c.refId || citationKindLabel(c)))]
            if (isGroundingCitation(c)) {
              parts.push(
                `<span class="src">${esc(
                  `desk grounding · ${citationKindLabel(c)} · resolves against ${
                    c.resolvesAgainst ?? "this finding's citation record"
                  }`,
                )}</span>`,
              )
            }
            if (c.source) parts.push(`<span class="src">${esc(c.source)}</span>`)
            if (typeof c.effectiveConfidence === 'number') {
              parts.push(`<span class="eff">eff ${Math.round(c.effectiveConfidence * 100)}%</span>`)
            }
            return `<li><span class="mk">${esc(c.marker)}</span> ${parts.join(' · ')}</li>`
          })
          .join('')}</ol>`
      : ''
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(
    doc.title || 'Legba Report',
  )}</title><style>
    body{font:14px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#111;max-width:720px;margin:32px auto;padding:0 20px;}
    h1{font-size:22px;margin:0 0 4px;} h2{font-size:16px;margin:20px 0 8px;border-bottom:1px solid #ddd;padding-bottom:2px;}
    h3{font-size:14px;margin:14px 0 6px;} .meta{color:#666;font-size:12px;margin-bottom:16px;}
    p{margin:0 0 10px;} ul,ol{margin:0 0 10px 22px;} li{margin:2px 0;}
    code{background:#f2f2f2;padding:1px 4px;border-radius:3px;font-size:.9em;}
    .evidence .mk{font-family:monospace;color:#2563eb;} .evidence .src{color:#666;font-size:.85em;} .evidence .eff{color:#666;font-size:.85em;}
    footer{margin-top:28px;color:#999;font-size:11px;border-top:1px solid #eee;padding-top:8px;}
    @media print{body{margin:0;}}
  </style></head><body>
    <h1>${esc(doc.title || 'Legba Report')}</h1>
    <div class="meta">${metaBits.join(' &middot; ')}${
      metaBits.length ? ' &middot; ' : ''
    }exported ${esc(new Date().toLocaleString())}</div>
    ${miniMarkdownToHtml(doc.body || '_(no written body)_')}
    ${evidence}
    <footer>Generated by Legba — a decompositional intelligence oracle.</footer>
  </body></html>`
}

/** Trigger a Blob object-URL download (Markdown / any text artifact). */
export function downloadText(filename: string, mime: string, content: string): void {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** Download the report as `.md`. */
export function downloadReportMarkdown(doc: ReportDoc): void {
  downloadText(`legba-${slug(doc.title)}-${stamp()}.md`, 'text/markdown', reportToMarkdown(doc))
}

/**
 * Open the report in a print window and invoke the browser print dialog (→ Save
 * as PDF). Returns false if the popup was blocked, so the caller can fall back to
 * the .md download. Best-effort by design (no bundled PDF engine).
 */
export function printReportPdf(doc: ReportDoc): boolean {
  const w = window.open('', '_blank', 'noopener,noreferrer,width=820,height=1000')
  if (!w) return false
  w.document.open()
  w.document.write(reportToPrintHtml(doc))
  w.document.close()
  // Let the document lay out before printing.
  w.focus()
  window.setTimeout(() => {
    try {
      w.print()
    } catch {
      /* user can print manually */
    }
  }, 250)
  return true
}
