#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Lewis George
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate ``docs/RELEASE_STATE.md`` — the single source of truth for the
counts external docs (README/FAQ) quote, READ-ONLY against the registry DB.

WHY: external reviewers caught the public README/FAQ saying "25 desks / 46
sources" while the live system runs 32 country desks (19 G20 + 13 watch) over
a 100-source catalog. Hand-updating prose counts every time a desk or source
is registered is exactly the kind of thing that silently drifts (nobody
remembers to grep every doc when `bringup_register_watch_country_targets.py`
grows the watch tier). The durable fix, per the pattern already established
by ``scripts/gen_release_state_matrix.py`` for the UI panel table: ONE
generator that reads the actual registered state and writes ONE doc; prose
docs quote *that* doc instead of a hand-typed number.

WHAT IS AND ISN'T DERIVED: every number in the generated sections below comes
from a SELECT against ``source_descriptors`` / ``target_descriptors`` /
``analyst_descriptors`` / ``legba_data_migrations`` / ``stack_components``
(all filtered to ``is_head AND state='active'`` where that predicate applies)
— nothing is hardcoded. Two structural facts are NOT stored as an explicit
flag anywhere and have to be inferred from a stable shape instead:

  * The "bounded reasoning units" are `analyst_descriptors.kind =
    'inline_target'` rows whose ``body.subscription.targets`` is a populated
    per-desk fan-out object (a `has_tag(...)` predicate) — this excludes the
    two OTHER `inline_target` analysts (`corpus_researcher`,
    `cross_doc_corroborator`) that are also inline-target-kind but are NOT
    per-desk fan-out units (their `subscription.targets` is JSON `null`).
    The COUNT is never written down here — it is `len(rows)`, so registering a
    ninth unit moves the heading without a code change. Which desk family each
    one works is likewise read off its own predicate (country coverage tag vs
    domain tag), not from a second list that could disagree.
  * "Same-model judging" is inferred by comparing each active analyst's
    ``method.llm.primary.raw`` stack-component id against its
    ``method.llm.verify.raw`` — reported true only when EVERY verify-bearing
    analyst's judge equals its own generator (never hardcoded to a
    known-today component id, so it keeps telling the truth if that changes).

Anything that is genuinely not mechanically derivable from descriptor state
or a small, explicit env-flag allowlist (roadmap language, "why" narrative,
UI panel maturity — already covered by RELEASE_STATE_MATRIX.md) is left OUT
of the generated file rather than guessed at; a short hand-maintained
"Declared" section marks that boundary explicitly so a reader never mistakes
prose for a generated fact.

READ-ONLY: this script only runs SELECT statements. It never writes to the
database.

Usage::

    PYTHONPATH=src python3 scripts/generate_release_manifest.py
    PYTHONPATH=src python3 scripts/generate_release_manifest.py --check   # exit 1 if stale

Env (same convention as the other DB-reading scripts, e.g.
``scripts/report_intrasource_dupes.py``):
  * ``LEGBA_DATA_PG_HOST`` (default ``127.0.0.1``)
  * ``LEGBA_DATA_PG_PORT`` (default ``5432``)
  * ``LEGBA_DATA_PG_USER`` (default ``legba``)
  * ``LEGBA_DATA_PG_PASSWORD`` (default ``legba``)
  * ``LEGBA_DATA_PG_DB`` (default ``legba``)
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path
from typing import Any

import asyncpg

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_MD = REPO_ROOT / "docs" / "RELEASE_STATE.md"

HEADER = "GENERATED by scripts/generate_release_manifest.py — do not hand-edit."

# A small, explicit allowlist of optional/experimental-feature env flags this
# generator is willing to report on. Deliberately NOT a blanket `os.environ`
# dump (that would leak deployment-specific values — hostnames, tokens —
# into a committed doc); each entry is a feature TOGGLE, not a secret or
# endpoint. Reported as "set" / "unset (default 0.0)" etc, never verbatim
# for anything that could carry a credential.
_ENV_FLAGS: tuple[tuple[str, str], ...] = (
    (
        "LEGBA_COMPOSITION_VERIFY_FLOOR",
        "composition-layer verify floor (default 0.0 = accept any faithfulness "
        "score; see meta_findings_synthesizer.DEFAULT_VERIFY_FLOOR)",
    ),
    (
        "LEGBA_WORLD_CONTEXT_DISABLED_UNITS",
        "per-run Tier-2 RAG auto-rollback kill-switch (comma-list of unit ids "
        "force-disabled; see src/legba/runtime/rag_rollback.py)",
    ),
)


async def _connect_pg() -> asyncpg.Connection:
    return await asyncpg.connect(
        host=os.environ.get("LEGBA_DATA_PG_HOST", "127.0.0.1"),
        port=int(os.environ.get("LEGBA_DATA_PG_PORT", "5432")),
        user=os.environ.get("LEGBA_DATA_PG_USER", "legba"),
        password=os.environ.get("LEGBA_DATA_PG_PASSWORD", "legba"),
        database=os.environ.get("LEGBA_DATA_PG_DB", "legba"),
    )


# ---------------------------------------------------------------------------
# Queries — each returns plain rows; all rendering happens in render_*().
# ---------------------------------------------------------------------------

_SOURCES_TOTAL_SQL = """
SELECT count(*) FROM source_descriptors WHERE is_head AND state = 'active'
"""

_SOURCES_BY_KIND_SQL = """
SELECT kind, count(*) AS n
FROM source_descriptors
WHERE is_head AND state = 'active'
GROUP BY kind
ORDER BY n DESC, kind
"""

# Country desks are the two bring-up-registered target families
# (country_g20_<iso2> / country_watch_<iso2>); tag membership drives the
# tier + nuclear-relevant subset counts (scripts/bringup_tag_targets.py).
_DESK_TAG_COUNTS_SQL = """
SELECT
    count(*) FILTER (WHERE body->'scope'->'tags' ? 'g20')            AS g20_n,
    count(*) FILTER (WHERE body->'scope'->'tags' ? 'watch')          AS watch_n,
    count(*) FILTER (WHERE body->'scope'->'tags' ? 'nuclear_watch')  AS nuclear_watch_n,
    count(*)                                                          AS total_n
FROM target_descriptors
WHERE is_head AND state = 'active'
  AND (descriptor_id LIKE 'country_g20_%' OR descriptor_id LIKE 'country_watch_%')
"""

# Every target that is NOT a country desk, at active OR draft. Two reasons
# this is one query rather than the old active-only "other targets" list:
#
#   * A domain pack (the supply-chain lanes/flows) registers targets that are
#     desks in every mechanical sense — an analyst subscription fans out over
#     them exactly like a country desk — but they must NOT inflate the country
#     count. Rendering splits them from the region/situation FRAMES by id
#     prefix and reports each group's tag set, so a future thematic pack shows
#     up here without a code change.
#   * DRAFT rows are included on purpose. A pack whose lanes an operator
#     activates one at a time is a real release-state fact, and an active-only
#     SELECT would render the un-activated majority invisible — which is
#     precisely the "prose drifted from registered state" failure this whole
#     generator exists to prevent. State is reported per row, never elided.
_NON_COUNTRY_TARGETS_SQL = """
SELECT descriptor_id, state,
       coalesce(
           (SELECT string_agg(t, ', ' ORDER BY t)
            FROM jsonb_array_elements_text(body->'scope'->'tags') AS t),
           ''
       ) AS tags
FROM target_descriptors
WHERE is_head AND state IN ('active', 'draft')
  AND descriptor_id NOT LIKE 'country_g20_%'
  AND descriptor_id NOT LIKE 'country_watch_%'
ORDER BY state, descriptor_id
"""

# The bounded reasoning units: inline_target analysts whose subscription
# fans out per-desk (a populated `targets` object) — excludes the two other
# inline_target analysts (corpus_researcher / cross_doc_corroborator) whose
# `targets` is JSON null (no per-desk fan-out). See module docstring.
_BOUNDED_UNITS_SQL = """
SELECT descriptor_id, name,
       body->'subscription'->'targets'->>'predicate' AS predicate
FROM analyst_descriptors
WHERE is_head AND state = 'active' AND kind = 'inline_target'
  AND jsonb_typeof(body->'subscription'->'targets') = 'object'
ORDER BY descriptor_id
"""

_COMPOSITION_LAYERS_SQL = """
SELECT descriptor_id, name
FROM analyst_descriptors
WHERE is_head AND state = 'active' AND kind = 'meta_findings_synthesizer'
ORDER BY descriptor_id
"""

_MIGRATION_HEAD_SQL = """
SELECT name FROM legba_data_migrations ORDER BY name DESC LIMIT 1
"""

_MIGRATION_COUNT_SQL = """
SELECT count(*) FROM legba_data_migrations
"""

# Verify configuration: every active analyst that declares method.llm.verify,
# plus its primary generator's stack-component id, so "same-model judge" is a
# COMPARISON, not an assumed constant.
_VERIFY_CONFIG_SQL = """
SELECT descriptor_id,
       body->'method'->'llm'->'primary'->>'raw' AS primary_raw,
       body->'method'->'llm'->'verify'->>'raw'  AS verify_raw
FROM analyst_descriptors
WHERE is_head AND state = 'active'
  AND body->'method'->'llm'->'verify' IS NOT NULL
ORDER BY descriptor_id
"""

# component_id ONLY — never the freeform `body->>'name'` display string.
# `name` is operator-authored prose and has been observed to embed
# deployment-internal notes (an inference-host fragment, in one live
# component's registered name); descriptor/stack IDENTIFIERS are the safe,
# stable thing to publish, never the free-text label riding along with them.
_STACK_COMPONENTS_SQL = """
SELECT component_id, kind
FROM stack_components
WHERE is_head AND state = 'active' AND kind = 'llm_provider'
ORDER BY component_id
"""

# Tier-1 (structured) grounding: analysts with grounding.enabled = true.
_GROUNDING_TIER1_SQL = """
SELECT descriptor_id
FROM analyst_descriptors
WHERE is_head AND state = 'active'
  AND (body->'grounding'->>'enabled')::boolean IS TRUE
ORDER BY descriptor_id
"""

# Tier-2 (vector RAG) grounding: analysts whose grounding.sources includes a
# "vector:<collection>" entry — currently only ever "vector:world_context".
# string_agg (not jsonb_agg) so asyncpg gets back a plain TEXT column —
# asyncpg does not auto-decode jsonb, so an aggregated jsonb array would come
# back as its literal JSON-text repr and iterate character-by-character.
_GROUNDING_TIER2_SQL = """
SELECT descriptor_id,
       (SELECT string_agg(s, ', ' ORDER BY s)
        FROM jsonb_array_elements_text(body->'grounding'->'sources') AS s
        WHERE s LIKE 'vector:%') AS vector_sources
FROM analyst_descriptors
WHERE is_head AND state = 'active'
  AND jsonb_typeof(body->'grounding'->'sources') = 'array'
  AND EXISTS (
      SELECT 1 FROM jsonb_array_elements_text(body->'grounding'->'sources') AS s
      WHERE s LIKE 'vector:%'
  )
ORDER BY descriptor_id
"""


async def gather(conn: asyncpg.Connection) -> dict[str, Any]:
    sources_total = await conn.fetchval(_SOURCES_TOTAL_SQL)
    sources_by_kind = await conn.fetch(_SOURCES_BY_KIND_SQL)
    desk_tags = await conn.fetchrow(_DESK_TAG_COUNTS_SQL)
    non_country_targets = await conn.fetch(_NON_COUNTRY_TARGETS_SQL)
    bounded_units = await conn.fetch(_BOUNDED_UNITS_SQL)
    composition_layers = await conn.fetch(_COMPOSITION_LAYERS_SQL)
    migration_head = await conn.fetchval(_MIGRATION_HEAD_SQL)
    migration_count = await conn.fetchval(_MIGRATION_COUNT_SQL)
    verify_rows = await conn.fetch(_VERIFY_CONFIG_SQL)
    stack_llm = await conn.fetch(_STACK_COMPONENTS_SQL)
    grounding_t1 = await conn.fetch(_GROUNDING_TIER1_SQL)
    grounding_t2 = await conn.fetch(_GROUNDING_TIER2_SQL)

    return {
        "sources_total": sources_total,
        "sources_by_kind": sources_by_kind,
        "desk_tags": desk_tags,
        "non_country_targets": non_country_targets,
        "bounded_units": bounded_units,
        "composition_layers": composition_layers,
        "migration_head": migration_head,
        "migration_count": migration_count,
        "verify_rows": verify_rows,
        "stack_llm": {r["component_id"] for r in stack_llm},
        "grounding_t1": grounding_t1,
        "grounding_t2": grounding_t2,
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render(data: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("# Release State")
    lines.append("")
    lines.append(f"<!-- {HEADER} -->")
    lines.append("")
    lines.append(
        f"_{HEADER} Regenerate with "
        "`PYTHONPATH=src python3 scripts/generate_release_manifest.py` "
        "after registering/retiring a source, desk, unit, or migration — "
        "every number below is a live SELECT against the registry DB "
        "(`is_head`, filtered to `state='active'` except where a row's state "
        "is reported explicitly), never hand-typed. README.md and "
        "docs/FAQ.md quote this file rather than repeating the numbers._"
    )
    lines.append("")

    # --- Sources ------------------------------------------------------
    lines.append("## Sources")
    lines.append("")
    lines.append(f"- **Active source descriptors: {data['sources_total']}**")
    lines.append("- By kind:")
    for row in data["sources_by_kind"]:
        lines.append(f"  - `{row['kind']}`: {row['n']}")
    lines.append("")

    # --- Desks ----------------------------------------------------------
    dt = data["desk_tags"]
    lines.append("## Country desks")
    lines.append("")
    lines.append(
        f"- **Total: {dt['total_n']}** — {dt['g20_n']} G20 + {dt['watch_n']} watch tier"
    )
    lines.append(f"- G20: {dt['g20_n']}")
    lines.append(f"- Watch tier: {dt['watch_n']}")
    lines.append(
        f"- `nuclear_watch`-tagged subset: {dt['nuclear_watch_n']} "
        "(the `proliferation_watch` unit's fan-out)"
    )
    # region_*/situation_* are cross-desk FRAMES the composition tower reads,
    # not desks an analyst fans out over; everything else non-country is a
    # thematic desk registered by a domain pack (rendered in its own section).
    non_country = data["non_country_targets"]
    frames = [
        r
        for r in non_country
        if r["descriptor_id"].startswith(("region_", "situation_"))
    ]
    _frame_ids = {r["descriptor_id"] for r in frames}
    thematic = [r for r in non_country if r["descriptor_id"] not in _frame_ids]
    active_frames = [r for r in frames if r["state"] == "active"]
    if active_frames:
        ids = ", ".join(f"`{r['descriptor_id']}`" for r in active_frames)
        lines.append(
            f"- Other active targets (region/situation frames, not desks, not "
            f"counted above): {len(active_frames)} — {ids}"
        )
    lines.append("")

    # --- Thematic (non-country) desks -----------------------------------
    if thematic:
        n_active = sum(1 for r in thematic if r["state"] == "active")
        lines.append(f"## Thematic desks ({len(thematic)} registered)")
        lines.append("")
        lines.append(
            f"- **Active: {n_active}** of {len(thematic)} registered — the "
            "remainder are registered `draft` and fan out only once an "
            "operator activates them."
        )
        lines.append("")
        lines.append("| Desk | State | Tags |")
        lines.append("|---|---|---|")
        for r in thematic:
            tags = ", ".join(f"`{t}`" for t in r["tags"].split(", ") if t)
            lines.append(
                f"| `{r['descriptor_id']}` | {r['state']} | {tags or '—'} |"
            )
        lines.append("")

    # --- Bounded units ----------------------------------------------------
    units = data["bounded_units"]
    lines.append(f"## Bounded reasoning units ({len(units)})")
    lines.append("")
    lines.append("| Unit | Name | Fan-out predicate |")
    lines.append("|---|---|---|")
    for r in units:
        lines.append(f"| `{r['descriptor_id']}` | {r['name']} | `{r['predicate']}` |")
    lines.append("")
    # Which desk family a unit fans out over is readable straight off its own
    # predicate — no second source of truth. A unit predicated on a country
    # COVERAGE tag works the country desks; one predicated on a domain tag
    # works the thematic desks. Split reported so "N units" is never mistaken
    # for "N units per country desk".
    _COVERAGE_TAGS = ('"g20"', '"watch"', '"nuclear_watch"')
    country_scoped = [
        r
        for r in units
        if any(t in (r["predicate"] or "") for t in _COVERAGE_TAGS)
    ]
    _country_scoped_ids = {r["descriptor_id"] for r in country_scoped}
    domain_scoped = [
        r for r in units if r["descriptor_id"] not in _country_scoped_ids
    ]
    split = f"- Country-desk-scoped: {len(country_scoped)}"
    if domain_scoped:
        ids = ", ".join(f"`{r['descriptor_id']}`" for r in domain_scoped)
        split += f" · domain-scoped (thematic desks): {len(domain_scoped)} — {ids}"
    lines.append(split)
    lines.append("")

    # --- Composition layers -------------------------------------------
    comps = data["composition_layers"]
    lines.append(f"## Composition layers ({len(comps)})")
    lines.append("")
    lines.append("| Layer | Name |")
    lines.append("|---|---|")
    for r in comps:
        lines.append(f"| `{r['descriptor_id']}` | {r['name']} |")
    lines.append("")

    # --- Schema / migration head ----------------------------------------
    lines.append("## Schema")
    lines.append("")
    lines.append(f"- Migration head: `{data['migration_head']}`")
    lines.append(f"- Applied migrations: {data['migration_count']}")
    lines.append("")

    # --- Verify configuration -------------------------------------------
    verify_rows = data["verify_rows"]
    stack_llm = data["stack_llm"]
    lines.append("## Verify configuration")
    lines.append("")
    lines.append(
        f"- Active analysts carrying a `method.llm.verify` pass: {len(verify_rows)}"
    )
    if verify_rows:
        same_model = all(r["primary_raw"] == r["verify_raw"] for r in verify_rows)
        judge_ids = sorted({r["verify_raw"] for r in verify_rows if r["verify_raw"]})
        judge_desc = ", ".join(f"`{jid}`" for jid in judge_ids)
        lines.append(
            f"- Judge route: {'SAME-MODEL' if same_model else 'MIXED'} "
            f"(every verify-bearing analyst's `method.llm.verify.raw` "
            f"{'equals' if same_model else 'does NOT always equal'} its own "
            "`method.llm.primary.raw`)"
        )
        lines.append(f"- Judge stack component(s) in use: {judge_desc}")
    other_llm = sorted(stack_llm - {r["verify_raw"] for r in verify_rows})
    if other_llm:
        unused_desc = ", ".join(f"`{c}`" for c in other_llm)
        lines.append(
            f"- Registered but NOT in the active verify route: {unused_desc}"
        )
    lines.append("")

    # --- Experimental / optional features (derivable) --------------------
    lines.append("## Experimental / optional features (derived)")
    lines.append("")
    t1 = data["grounding_t1"]
    t2 = data["grounding_t2"]
    unit_ids = {r["descriptor_id"] for r in units}
    t1_units = sorted(unit_ids & {r["descriptor_id"] for r in t1})
    lines.append(
        f"- Tier-1 (structured) knowledge grounding enabled: {len(t1)} active "
        f"analysts, including {len(t1_units)}/{len(units)} bounded units "
        f"({', '.join(f'`{u}`' for u in t1_units) if t1_units else 'none'})"
    )
    if t2:
        for r in t2:
            lines.append(
                f"- Tier-2 (vector RAG) grounding pilot: `{r['descriptor_id']}` "
                f"— `{r['vector_sources']}`"
            )
    else:
        lines.append("- Tier-2 (vector RAG) grounding pilot: none active")
    for env_name, desc in _ENV_FLAGS:
        val = os.environ.get(env_name)
        state = f"set = `{val}`" if val is not None else "unset (default applies)"
        lines.append(f"- `{env_name}` ({desc}): {state}")
    lines.append("")
    lines.append(
        "_Env-flag values above reflect the environment THIS SCRIPT ran in — "
        "if generated outside the runtime container, an unset flag means "
        "\"not overridden here\", not necessarily \"unset in production\"._"
    )
    lines.append("")

    # --- Declared (hand-maintained) --------------------------------------
    lines.append("## Declared (hand-maintained — NOT generated)")
    lines.append("")
    lines.append(
        "Everything above this section is a live SELECT against the registry "
        "DB. The following is NOT mechanically derivable from descriptor "
        "state or env flags and is maintained by the operator; treat it as "
        "narrative, not fact:"
    )
    lines.append("")
    lines.append(
        "- UI panel maturity (live/preview/hidden) — see "
        "`docs/RELEASE_STATE_MATRIX.md` (generated from `registry.ts`, a "
        "separate generator)."
    )
    lines.append(
        "- Declared-not-built seams and known limitations — see `docs/SEAMS.md`."
    )
    lines.append(
        "- Roadmap / planned work (e.g. a dedicated cross-family verify "
        "judge) — see `docs/STATUS.md` and `docs/DESIGN.md`."
    )
    lines.append("")

    return "\n".join(lines) + "\n"


async def main_async(check: bool) -> int:
    conn = await _connect_pg()
    try:
        data = await gather(conn)
    finally:
        await conn.close()

    new_text = render(data)
    current_text = OUT_MD.read_text(encoding="utf-8") if OUT_MD.exists() else None

    if current_text == new_text:
        print(f"{OUT_MD.relative_to(REPO_ROOT)} is current.")
        return 0

    if check:
        print(
            f"{OUT_MD.relative_to(REPO_ROOT)} is STALE relative to the live "
            "registry DB — run `python3 scripts/generate_release_manifest.py` "
            "to regenerate.",
            file=sys.stderr,
        )
        return 1

    OUT_MD.write_text(new_text, encoding="utf-8")
    print(f"Wrote {OUT_MD.relative_to(REPO_ROOT)}.")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 (no write) if regenerating would change the file.",
    )
    args = ap.parse_args(argv)
    return asyncio.run(main_async(args.check))


if __name__ == "__main__":
    raise SystemExit(main())
